services:
  - type: web
    name: drexcape-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000

  - type: web
    name: drexcape-frontend
    env: static
    buildCommand: cd drexcape && npm cache clean --force && npm install --legacy-peer-deps && npm run build && cp public/_redirects dist/ && cp public/_headers dist/ && cp public/404.html dist/
    staticPublishPath: dist
    envVars:
      - key: NODE_ENV
        value: production 